"""Add GST and biller details to SalesBill

Revision ID: 2ee15ca6a42a
Revises: e3ebc9d76739
Create Date: 2026-03-06 01:01:09.906142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee15ca6a42a'
down_revision: Union[str, None] = 'e3ebc9d76739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_bills', sa.Column('gst_amount', sa.Float(), nullable=True))
    op.add_column('sales_bills', sa.Column('taxable_amount', sa.Float(), nullable=True))
    op.add_column('sales_bills', sa.Column('biller_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_bills', 'biller_name')
    op.drop_column('sales_bills', 'taxable_amount')
    op.drop_column('sales_bills', 'gst_amount')
    # ### end Alembic commands ###
