"""Add Customer table

Revision ID: b6f22cd53f5a
Revises: 2ee15ca6a42a
Create Date: 2026-03-06 01:11:15.263181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f22cd53f5a'
down_revision: Union[str, None] = '2ee15ca6a42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
